package runtime

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/thy-bupt/llmberth/internal/admin"
	"github.com/thy-bupt/llmberth/internal/scaffold"
)

// Severity of a check result.
type Severity int

const (
	// Ok means the check passed.
	Ok Severity = iota
	// Warn means degraded but usable.
	Warn
	// Fail blocks the operation.
	Fail
)

func (s Severity) String() string {
	switch s {
	case Warn:
		return "warn"
	case Fail:
		return "fail"
	default:
		return "ok"
	}
}

// Check is one doctor finding.
type Check struct {
	Name  string
	Sev   Severity
	Detail string
}

// DoctorResult carries all findings.
type DoctorResult struct {
	Checks []Check
}

// HasFail reports whether any check failed.
func (d DoctorResult) HasFail() bool {
	for _, c := range d.Checks {
		if c.Sev == Fail {
			return true
		}
	}
	return false
}

func (d DoctorResult) summary() (ok, warn, fail int) {
	for _, c := range d.Checks {
		switch c.Sev {
		case Ok:
			ok++
		case Warn:
			warn++
		case Fail:
			fail++
		}
	}
	return
}

// Render prints the checks in human-readable form.
func (d DoctorResult) Render(out io.Writer) {
	ok, warn, fail := d.summary()
	symbols := map[Severity]string{Ok: "✓", Warn: "!", Fail: "✗"}
	for _, c := range d.Checks {
		detail := ""
		if c.Detail != "" {
			detail = " — " + c.Detail
		}
		fmt.Fprintf(out, "  %s %s%s\n", symbols[c.Sev], c.Name, detail)
	}
	fmt.Fprintf(out, "\n%d ok, %d warning(s), %d failure(s)\n", ok, warn, fail)
}

// RequiredEnvKeys are the keys every generated project's .env must carry.
// Mirrors the template's .env.example; doctor flags missing/empty ones.
var RequiredEnvKeys = []string{
	"POSTGRES_PASSWORD",
	"DATABASE_URL",
	"ADMIN_TOKEN",
	"LLM_PROVIDER",
	"LLM_MODEL",
}

// requiredEnvKeys returns the keys every .env must carry.
func requiredEnvKeys() []string { return RequiredEnvKeys }

// RunDoctor executes the basic health checks (M2 scope; the --security
// 12-point audit is M4). Checks: docker/compose, project structure, .env
// completeness, admin token consistency, app/admin reachability.
func RunDoctor(ctx context.Context, projectDir string) (DoctorResult, error) {
	res := DoctorResult{}

	// 1. docker + compose v2.
	if err := ComposeAvailable(); err != nil {
		res.Checks = append(res.Checks, Check{Name: "docker + compose v2", Sev: Fail, Detail: err.Error()})
	} else {
		res.Checks = append(res.Checks, Check{Name: "docker + compose v2", Sev: Ok})
	}

	// 2. project structure.
	mPath := filepath.Join(projectDir, scaffold.ManifestFileName)
	manifest, err := scaffold.LoadManifest(mPath)
	switch {
	case os.IsNotExist(err):
		res.Checks = append(res.Checks, Check{Name: "project manifest", Sev: Fail,
			Detail: fmt.Sprintf("no %s in %s — run inside a llmberth project", scaffold.ManifestFileName, projectDir)})
	case err != nil:
		res.Checks = append(res.Checks, Check{Name: "project manifest", Sev: Fail, Detail: err.Error()})
	default:
		res.Checks = append(res.Checks, Check{Name: "project manifest", Sev: Ok,
			Detail: fmt.Sprintf("v%d, generated by %s", manifest.Version, manifest.GeneratedBy)})
	}

	// 3. .env completeness (plan M2 acceptance: doctor reports missing keys).
	envPath := filepath.Join(projectDir, ".env")
	envVals, envErr := readEnvFile(envPath)
	switch {
	case os.IsNotExist(envErr):
		res.Checks = append(res.Checks, Check{Name: ".env present", Sev: Fail,
			Detail: "missing — copy .env.example to .env (init normally creates it)"})
	case envErr != nil:
		res.Checks = append(res.Checks, Check{Name: ".env present", Sev: Fail, Detail: envErr.Error()})
	default:
		var missing []string
		for _, k := range requiredEnvKeys() {
			if v, ok := envVals[k]; !ok || strings.TrimSpace(v) == "" {
				missing = append(missing, k)
			}
		}
		if len(missing) > 0 {
			res.Checks = append(res.Checks, Check{Name: ".env required keys", Sev: Fail,
				Detail: "missing or empty: " + strings.Join(missing, ", ")})
		} else {
			res.Checks = append(res.Checks, Check{Name: ".env required keys", Sev: Ok,
				Detail: fmt.Sprintf("%d keys checked, values not displayed", len(requiredEnvKeys()))})
		}
	}

	// 4. admin token file + consistency with .env.
	token, tokenErr := admin.LoadToken(projectDir)
	if tokenErr != nil {
		res.Checks = append(res.Checks, Check{Name: "admin token file", Sev: Fail, Detail: tokenErr.Error()})
	} else if envVals != nil {
		if envToken := envVals["ADMIN_TOKEN"]; strings.TrimSpace(envToken) != token {
			res.Checks = append(res.Checks, Check{Name: "admin token file", Sev: Warn,
				Detail: "token file and .env ADMIN_TOKEN differ — the CLI will get 401s until they match"})
		} else {
			res.Checks = append(res.Checks, Check{Name: "admin token file", Sev: Ok, Detail: "consistent with .env"})
		}
	} else {
		res.Checks = append(res.Checks, Check{Name: "admin token file", Sev: Ok})
	}

	// 5. reachability (only meaningful when the stack is running).
	if manifest.Services.App.Port > 0 {
		appUp := probe(ctx, fmt.Sprintf("http://127.0.0.1:%d/healthz", manifest.Services.App.Port))
		adminUp := probe(ctx, fmt.Sprintf("http://127.0.0.1:%d/admin/health", manifest.Services.App.AdminPort))
		switch {
		case appUp && adminUp:
			res.Checks = append(res.Checks, Check{Name: "app + admin API reachable", Sev: Ok,
				Detail: fmt.Sprintf("ports %d/%d", manifest.Services.App.Port, manifest.Services.App.AdminPort)})
		case !appUp && !adminUp:
			res.Checks = append(res.Checks, Check{Name: "stack reachable", Sev: Warn,
				Detail: "not running — start with `llmberth up` or docker compose up -d"})
		case appUp && !adminUp:
			res.Checks = append(res.Checks, Check{Name: "admin API reachable", Sev: Fail,
				Detail: "app answers but the admin API does not — check ADMIN_PORT binding"})
		default:
			res.Checks = append(res.Checks, Check{Name: "app reachable", Sev: Fail,
				Detail: "admin API answers but the public app does not"})
		}
	}

	return res, nil
}

// probe does a 2s GET expecting any HTTP response.
func probe(ctx context.Context, url string) bool {
	cCtx, cancel := context.WithTimeout(ctx, 2*time.Second)
	defer cancel()
	req, err := http.NewRequestWithContext(cCtx, http.MethodGet, url, nil)
	if err != nil {
		return false
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return false
	}
	_ = resp.Body.Close()
	return true
}

// readEnvFile parses KEY=VALUE lines (comments ignored). Returns nil when
// the file cannot be read; values are never logged by callers.
func readEnvFile(path string) (map[string]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer func() { _ = f.Close() }()
	out := map[string]string{}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		out[strings.TrimSpace(k)] = strings.TrimSpace(v)
	}
	return out, sc.Err()
}
