package scaffold

import (
	"fmt"
	"io/fs"
	"path"
	"strings"
	"text/template"
)

// Engine renders the embedded template tree into a target directory.
type Engine struct {
	// FS is the template source filesystem (template.FS in production, a
	// test FS in unit tests).
	FS fs.FS
	// Root is the sub-directory of FS holding the template sources.
	Root string
	// TemplateVersion stamped into the manifest.
	TemplateVersion string
	// CLIVersion stamped into the manifest.
	CLIVersion string
}

// GeneratedFile records one rendered output path (relative to target root).
type GeneratedFile struct {
	RelPath string
}

// conditionalDirs maps wrapper directory names in the template tree to a
// predicate on Options. When the predicate is false the whole subtree is
// skipped; when true the wrapper segment is stripped from the output path.
func conditionalDirs(o Options) map[string]bool {
	return map[string]bool{
		"__ui__": o.UI == "single-page",
	}
}

// tmplData is the value exposed to every .tmpl file.
type tmplData struct {
	Name       string
	Module     string
	Provider   ProviderPreset
	UI         string
	HasUI      bool
	DB         string
	AdminToken string
	DBPassword string
	Manifest   Manifest
}

// Generate renders the whole tree into targetDir (which must be empty or
// nonexistent). adminToken and dbPassword are freshly generated secrets
// baked into the generated project's .env; they are generated by the caller
// (keys package) because the caller also persists its own copy of the admin
// token for CLI use.
func (e *Engine) Generate(opts Options, targetDir string, force bool, adminToken, dbPassword string) ([]GeneratedFile, Manifest, error) {
	if err := opts.Validate(); err != nil {
		return nil, Manifest{}, fmt.Errorf("invalid options: %w", err)
	}
	preset, err := Preset(opts.Provider)
	if err != nil {
		return nil, Manifest{}, err
	}
	manifest := NewManifest(opts, e.CLIVersion, e.TemplateVersion)

	if err := ensureEmptyDir(targetDir, force); err != nil {
		return nil, Manifest{}, err
	}

	data := tmplData{
		Name:       opts.Name,
		Module:     opts.Module,
		Provider:   preset,
		UI:         opts.UI,
		HasUI:      opts.UI == "single-page",
		DB:         opts.DB,
		AdminToken: adminToken,
		DBPassword: dbPassword,
		Manifest:   manifest,
	}

	var written []GeneratedFile
	err = fs.WalkDir(e.FS, e.Root, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		relIn := strings.TrimPrefix(strings.TrimPrefix(p, e.Root), "/")
		if relIn == "" {
			return nil
		}
		outRel, isTmpl, ok := e.mapPath(relIn, opts)
		if !ok {
			return nil
		}

		src, err := e.FS.Open(p)
		if err != nil {
			return fmt.Errorf("open template %s: %w", p, err)
		}
		defer func() { _ = src.Close() }() // read-only handle in walk callback

		absOut := path.Join(targetDir, outRel)
		if isTmpl {
			tmpl, err := template.New(path.Base(p)).Parse(srcToText(e.FS, p))
			if err != nil {
				return fmt.Errorf("parse template %s: %w", p, err)
			}
			if err := renderToFile(tmpl, data, absOut); err != nil {
				return fmt.Errorf("render %s: %w", p, err)
			}
		} else {
			if err := copyToFile(e.FS, p, absOut); err != nil {
				return fmt.Errorf("copy %s: %w", p, err)
			}
		}
		written = append(written, GeneratedFile{RelPath: outRel})
		return nil
	})
	if err != nil {
		return nil, Manifest{}, fmt.Errorf("walk template tree: %w", err)
	}
	return written, manifest, nil
}

// mapPath converts a template-relative input path to an output path,
// resolving conditional directories and the .tmpl marker. ok=false means
// skip the file entirely; isTmpl reports whether the file must be rendered.
func (e *Engine) mapPath(relIn string, opts Options) (outPath string, isTmpl, ok bool) {
	isTmpl = strings.HasSuffix(relIn, ".tmpl")
	if isTmpl {
		relIn = strings.TrimSuffix(relIn, ".tmpl")
	}
	segs := strings.Split(relIn, "/")
	conds := conditionalDirs(opts)
	out := make([]string, 0, len(segs))
	for _, seg := range segs {
		if enable, isCond := conds[seg]; isCond {
			if !enable {
				return "", false, false
			}
			continue // strip wrapper
		}
		out = append(out, seg)
	}
	return strings.Join(out, "/"), isTmpl, true
}
